<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Data curation: Extended Data Table 1 to a phyloseq object</title>

<script src="site_libs/header-attrs-2.31/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.5.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">repdist</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html#installation">Install</a>
</li>
<li>
  <a href="data_curation.html">Data curation</a>
</li>
<li>
  <a href="case_study.html">Case study</a>
</li>
<li>
  <a href="index.html#reproducing">Reproducing</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/Yixuan39/repdist">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Data curation: Extended Data Table 1 to a
phyloseq object</h1>

</div>


<pre class="r"><code>library(phyloseq)
library(vegan)
library(permute)
HERE &lt;- file.path(&quot;data&quot;, &quot;test_study&quot;)</code></pre>
<p>Source: Blakeley-Ruiz <em>et al.</em>, <em>ISME J</em>
<strong>19</strong>(1), wraf048, “Dietary protein source alters gut
microbiota composition and function”.</p>
<p><strong>Extended Data Table 1</strong> is the abundance source. Its
sample columns are peptide-spectral-match <strong>counts</strong> —
unrarefied spectral counts summed per taxon is what the paper calls
“proteinaceous biomass” (see below) — and it carries amino-acid
sequences inline. <strong>Extended Data Table 6</strong> publishes
microbe-restricted %NSAF, a different abundance normalization not used
here; it is loaded only for its curated GTDB lineage per protein, joined
onto Table 1’s proteins by id.</p>
<p>This report builds the phyloseq object and checks it against the
published PERMANOVA. If that check fails nothing downstream is worth
running, so it lives here rather than in the analysis. Output:
<code>data/test_study/ps.rds</code>.</p>
<div id="reading-the-table" class="section level1">
<h1>Reading the table</h1>
<p>Two title lines, a header on line 3, five annotation columns, then
one column per sample. Blank cells are zeros. Column 1 codes each
protein <code>Diet</code>, <code>DietLlactis</code>, <code>Host</code>
or <code>Microbiome</code>; only microbial proteins are kept, matching
the published microbiota analysis.</p>
<pre class="r"><code>raw &lt;- read.delim(file.path(HERE, &quot;ExtendedDataTable1CompleteMetaproteome.txt&quot;),
                  skip = 2, quote = &quot;\&quot;&quot;, check.names = FALSE,
                  colClasses = &quot;character&quot;, comment.char = &quot;&quot;)
names(raw)[1:5] &lt;- c(&quot;code&quot;, &quot;protein_id&quot;, &quot;aa_length&quot;, &quot;description&quot;, &quot;sequence&quot;)
raw &lt;- raw[raw$code == &quot;Microbiome&quot;, ]

counts &lt;- vapply(raw[, -(1:5)], function(x) {
  blank &lt;- !nzchar(trimws(x))                  # blank cell = protein not seen
  v &lt;- suppressWarnings(as.numeric(x))
  bad &lt;- is.na(v) &amp; !blank                      # a parse failure that ISN&#39;T blank is
  if (any(bad))                                 # unexpected data, not a documented zero
    stop(&quot;Non-numeric, non-blank count cell(s): &quot;,
         paste(unique(x[bad]), collapse = &quot;, &quot;), call. = FALSE)
  v[blank] &lt;- 0
  v
}, numeric(nrow(raw)))
stopifnot(all(counts &gt;= 0), all(counts == round(counts)))  # PSM counts only
storage.mode(counts) &lt;- &quot;integer&quot;
dimnames(counts) &lt;- list(raw$protein_id, names(raw)[-(1:5)])

c(proteins = nrow(counts), samples = ncol(counts), total_psm = sum(counts))</code></pre>
<pre><code>##  proteins   samples total_psm 
##     30561       111   1813826</code></pre>
</div>
<div id="design-from-the-sample-names" class="section level1">
<h1>Design, from the sample names</h1>
<p>Names are <code>{cage}_{mouse}_{diet}</code>,
e.g. <code>C2_1_20RIC</code>. The diet token gives both the protein
source and its percentage, and — through the published feeding order —
the period, which is what <code>age_week</code> needs. <code>T0</code>
is the pre-intervention baseline on standard chow; <code>CTL</code> is
the repeat feeding at study end, 20% soy for C1/C2 and 20% casein for
C3/C4.</p>
<p>The ninth diet, 20% chicken bone, caused weight loss, was stopped
after three days and yielded no samples, so no token exists for it.</p>
<pre class="r"><code>diets &lt;- data.frame(
  token  = c(&quot;T0&quot;, &quot;20SOY&quot;, &quot;20CAS&quot;, &quot;20RIC&quot;, &quot;40SOY&quot;, &quot;20YST&quot;, &quot;40CAS&quot;, &quot;20PEA&quot;,
             &quot;20EGG&quot;, &quot;CTL&quot;),
  period = 0:9,
  diet   = c(NA, &quot;Soy&quot;, &quot;Casein&quot;, &quot;Rice&quot;, &quot;Soy&quot;, &quot;Yeast&quot;, &quot;Casein&quot;, &quot;Pea&quot;, &quot;Egg&quot;, NA),
  dose   = c(NA, &quot;20&quot;, &quot;20&quot;, &quot;20&quot;, &quot;40&quot;, &quot;20&quot;, &quot;40&quot;, &quot;20&quot;, &quot;20&quot;, &quot;20&quot;),
  phase  = c(&quot;baseline&quot;, rep(&quot;treatment&quot;, 8), &quot;control&quot;))

f &lt;- strsplit(colnames(counts), &quot;_&quot;)
cage  &lt;- vapply(f, `[`, &quot;&quot;, 1)
token &lt;- vapply(f, `[`, &quot;&quot;, 3)
stopifnot(token %in% diets$token)

md &lt;- data.frame(diets[match(token, diets$token), c(&quot;period&quot;, &quot;phase&quot;, &quot;diet&quot;, &quot;dose&quot;)],
                 sample_id = colnames(counts), cage = cage,
                 subject = paste(cage, vapply(f, `[`, &quot;&quot;, 2), sep = &quot;_&quot;),
                 # sex is not in the name and is not free to vary; it is also the
                 # paper&#39;s &quot;mouse group&quot;, the sexes having come from different rooms
                 sex = ifelse(cage %in% c(&quot;C1&quot;, &quot;C3&quot;), &quot;Male&quot;, &quot;Female&quot;),
                 row.names = colnames(counts))
# control re-feeds take their source from the cage
md$diet[md$phase == &quot;control&quot;] &lt;- ifelse(cage[md$phase == &quot;control&quot;] %in% c(&quot;C1&quot;, &quot;C2&quot;),
                                         &quot;Soy&quot;, &quot;Casein&quot;)
# adonis2 on a continuous term is invariant to a constant shift, so weeks-since-T0
# stands in for age. The bone week still elapsed, so CTL sits two weeks after period 8.
md$age_week &lt;- ifelse(md$period == 9, 10L, md$period)

table(md$period, md$diet, useNA = &quot;ifany&quot;)</code></pre>
<pre><code>##    
##     Casein Egg Pea Rice Soy Yeast &lt;NA&gt;
##   0      0   0   0    0   0     0   12
##   1      0   0   0    0  12     0    0
##   2     12   0   0    0   0     0    0
##   3      0   0   0   10   0     0    0
##   4      0   0   0    0  11     0    0
##   5      0   0   0    0   0    11    0
##   6     11   0   0    0   0     0    0
##   7      0   0  11    0   0     0    0
##   8      0  10   0    0   0     0    0
##   9      5   0   0    0   6     0    0</code></pre>
<p><code>C3_1</code> contributes 3 samples and <code>C4_2</code> 8; the
other ten mice contribute 10 each.</p>
</div>
<div id="bins" class="section level1">
<h1>Bins</h1>
<p>Protein ids encode the MAG bin (<code>AB1-1_Cage2_bin.36_00001</code>
-&gt; <code>AB1-1_Cage2_bin.36</code>), so the bin is recoverable from
the id alone. But a bin is per-assembly, not per-species: the same
organism gets a different bin number in every cage it was assembled in,
so <code>Bin</code> over-splits whatever it is used as a stand-in for
species.</p>
<p>Extended Data Table 6 carries a real GTDB lineage per protein,
curated rather than parsed from an id, and does not have that problem –
the same species gets the same lineage string regardless of which cage’s
assembly it came from. It has no counts of its own (§ intro), so it is
loaded here only for its five annotation columns, joined onto Table 1’s
proteins by protein id.</p>
<pre class="r"><code>bin &lt;- sub(&quot;_[0-9]+$&quot;, &quot;&quot;, rownames(counts))

t6 &lt;- read.delim(file.path(HERE, &quot;annotated&quot;, &quot;ExtendedDataTable6AnnotatedMicrobialMetaproteomes.txt&quot;),
                 skip = 2, quote = &quot;\&quot;&quot;, check.names = FALSE, colClasses = &quot;character&quot;,
                 comment.char = &quot;&quot;, fileEncoding = &quot;latin1&quot;)
lineage &lt;- setNames(t6[[&quot;Taxa Lineage&quot;]], t6[[&quot;Protein Identifier&quot;]])[rownames(counts)]

ranks &lt;- c(&quot;Domain&quot;, &quot;Phylum&quot;, &quot;Class&quot;, &quot;Order&quot;, &quot;Family&quot;, &quot;Genus&quot;, &quot;Species&quot;)
rk &lt;- t(vapply(strsplit(lineage, &quot;;&quot;), function(x) {
  x &lt;- sub(&quot;^[a-z]__&quot;, &quot;&quot;, x)
  x[!nzchar(x)] &lt;- NA
  length(x) &lt;- length(ranks)
  x
}, character(length(ranks))))
dimnames(rk) &lt;- list(rownames(counts), ranks)

tax &lt;- cbind(Bin = bin, rk)
c(bins = length(unique(bin)), genera = length(unique(na.omit(tax[, &quot;Genus&quot;]))),
 unmatched = sum(is.na(lineage)), proteins = nrow(tax))</code></pre>
<pre><code>##      bins    genera unmatched  proteins 
##       750        64      8529     30561</code></pre>
<p>8529 of 30561 proteins have no Table 6 entry and stay unclassified at
every rank; <code>Bin</code> is unaffected and still covers all of
them.</p>
<div id="no-tree" class="section level2">
<h2>No phylogenetic tree</h2>
<p><code>phy_tree</code> is the one phyloseq slot this dataset cannot
fill honestly, and both routes were measured before being abandoned.</p>
<p>Aligning the proteins (<code>DECIPHER::AlignSeqs</code> →
<code>Treeline</code>, the 16S idiom) assumes the features are
homologous. They are not: the 200 most abundant proteins align to
<strong>4236 columns for a mean length of 589 — 86% gaps</strong>,
non-homologous sequences gapping past each other. A tree from that is a
similarity dendrogram, not a phylogeny.</p>
<p>A GTDB taxonomy cladogram over bins fails worse. Measured while Table
6’s lineages were still loaded: only <strong>415 of 750 bins</strong>
carry one, so dropping the unplaceable bins costs a <strong>median 33%
of each sample’s mass</strong>, and that loss is strongly
<strong>diet-associated</strong> — mean retention 31% on Yeast against
73% on Pea, ANOVA <span class="math inline">\(p =
4\times10^{-24}\)</span>. Weighted UniFrac on that tree would read a
diet-confounded classification-coverage artifact as composition: a
larger confound than the sequencing depth rarefaction exists to remove.
That measurement is why the lineages are no longer carried at all.</p>
<p>So there is no weighted UniFrac here. This is the motivation for the
method rather than an obstacle to it — relatedness at protein resolution
has essentially no tree-based option, which is why the ground metric is
a continuous representation space.</p>
</div>
</div>
<div id="the-phyloseq-object" class="section level1">
<h1>The phyloseq object</h1>
<pre class="r"><code>ps &lt;- phyloseq(otu_table(counts, taxa_are_rows = TRUE),
               sample_data(md),
               tax_table(tax),
               refseq(Biostrings::AAStringSet(setNames(raw$sequence, raw$protein_id))))
ps</code></pre>
<pre><code>## phyloseq-class experiment-level object
## otu_table()   OTU Table:         [ 30561 taxa and 111 samples ]
## sample_data() Sample Data:       [ 111 samples by 9 sample variables ]
## tax_table()   Taxonomy Table:    [ 30561 taxa by 8 taxonomic ranks ]
## refseq()      AAStringSet:      [ 30561 reference sequences ]</code></pre>
<pre class="r"><code>saveRDS(ps, file.path(HERE, &quot;ps.rds&quot;))</code></pre>
</div>
<div id="checking-against-the-published-result" class="section level1">
<h1>Checking against the published result</h1>
<blockquote>
<p>“A Bray–Curtis dissimilarity matrix calculated from proteinaceous
biomasses of species in the microbiota was analyzed, using the adonis2
function in the vegan package in R, to test for the effect of protein
source, amount of protein, mouse group, or age (in weeks) on microbiota
composition. The strata function was used to account for repeated
measures.”</p>
</blockquote>
<p>Their <code>df</code> fixes the coding: protein source at df 7 means
8 levels, not the 6 diets, and amount at df 2 means 3 — which only works
if T0 is in the model with its own level of each. So source is the six
proteins plus <code>chow</code> and <code>control</code>, and all 111
samples are used.</p>
<p><code>tax_glom()</code> needs more than one rank to work with, so the
proteins are summed onto their real taxon directly — the finest lineage
rank Table 6 resolved. A protein with no Table 6 lineage falls back to
its own <code>Bin</code> rather than a shared <code>Unclassified</code>
bucket: merging only happens where the lineage says two proteins are the
same organism, so proteins nobody could place don’t get treated as each
other’s evidence. (A single pooled <code>Unclassified</code> bucket was
tried first and fits the published numbers visibly worse — 28% of
proteins have no lineage, and merging them regardless of their real,
probably different, organisms adds noise a per-cage <code>Bin</code>
fallback avoids.)</p>
<pre class="r"><code>tx  &lt;- as(tax_table(ps), &quot;matrix&quot;)
lin &lt;- tx[, c(&quot;Domain&quot;, &quot;Phylum&quot;, &quot;Class&quot;, &quot;Order&quot;, &quot;Family&quot;, &quot;Genus&quot;, &quot;Species&quot;)]
taxon &lt;- apply(lin, 1, function(x) paste(x[!is.na(x)], collapse = &quot;;&quot;))
taxon &lt;- ifelse(nzchar(taxon), taxon, tx[, &quot;Bin&quot;])

taxa_ab &lt;- rowsum(as(otu_table(ps), &quot;matrix&quot;), taxon)
n_taxa  &lt;- nrow(taxa_ab)
taxa_ab &lt;- t(taxa_ab) / colSums(taxa_ab)          # samples in rows, relative abundance

m &lt;- data.frame(sample_data(ps))
m$source &lt;- ifelse(m$phase == &quot;baseline&quot;, &quot;chow&quot;,
            ifelse(m$phase == &quot;control&quot;, &quot;control&quot;, m$diet))
m$amount &lt;- ifelse(is.na(m$dose), &quot;chow&quot;, m$dose)

set.seed(1)
a &lt;- adonis2(vegdist(taxa_ab, &quot;bray&quot;) ~ source + amount + sex + age_week,
             data = m, by = &quot;terms&quot;,
             permutations = how(blocks = factor(m$subject), nperm = 9999))
a</code></pre>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Df</th>
<th align="right">SumOfSqs</th>
<th align="right">R2</th>
<th align="right">F</th>
<th align="right">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">source</td>
<td align="right">7</td>
<td align="right">8.9167607</td>
<td align="right">0.4091293</td>
<td align="right">14.597650</td>
<td align="right">0.0001</td>
</tr>
<tr class="even">
<td align="left">amount</td>
<td align="right">1</td>
<td align="right">0.1600379</td>
<td align="right">0.0073430</td>
<td align="right">1.833989</td>
<td align="right">0.0871</td>
</tr>
<tr class="odd">
<td align="left">sex</td>
<td align="right">1</td>
<td align="right">3.8431696</td>
<td align="right">0.1763368</td>
<td align="right">44.041634</td>
<td align="right">0.0001</td>
</tr>
<tr class="even">
<td align="left">age_week</td>
<td align="right">1</td>
<td align="right">0.1482935</td>
<td align="right">0.0068042</td>
<td align="right">1.699402</td>
<td align="right">0.1006</td>
</tr>
<tr class="odd">
<td align="left">Residual</td>
<td align="right">100</td>
<td align="right">8.7262194</td>
<td align="right">0.4003867</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">Total</td>
<td align="right">110</td>
<td align="right">21.7944812</td>
<td align="right">1.0000000</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
</div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">paper_df</th>
<th align="right">paper_R2</th>
<th align="right">paper_F</th>
<th align="right">df</th>
<th align="right">R2</th>
<th align="right">F</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">source</td>
<td align="right">7</td>
<td align="right">0.39</td>
<td align="right">15.0</td>
<td align="right">7</td>
<td align="right">0.409</td>
<td align="right">14.6</td>
</tr>
<tr class="even">
<td align="left">amount</td>
<td align="right">2</td>
<td align="right">0.01</td>
<td align="right">2.2</td>
<td align="right">1</td>
<td align="right">0.007</td>
<td align="right">1.8</td>
</tr>
<tr class="odd">
<td align="left">sex</td>
<td align="right">1</td>
<td align="right">0.21</td>
<td align="right">56.9</td>
<td align="right">1</td>
<td align="right">0.176</td>
<td align="right">44.0</td>
</tr>
<tr class="even">
<td align="left">age_week</td>
<td align="right">1</td>
<td align="right">0.01</td>
<td align="right">2.5</td>
<td align="right">1</td>
<td align="right">0.007</td>
<td align="right">1.7</td>
</tr>
</tbody>
</table>
</div>
<p>Source, mouse group and age land close to the published values,
against 464 taxa — real lineage where Table 6 resolved one,
<code>Bin</code> otherwise, so still finer than their 161 dereplicated
species (per-cage assembly still splits organisms Table 6 couldn’t
place, just fewer of them than before).</p>
<p>The one term that does not match is <code>amount</code>, at df 1
against their 2: coding T0 as its own level of <em>both</em> source and
amount makes the two collinear, and the sequential fit gives the shared
degree of freedom to whichever enters first. The variance explained is
unchanged, so this is a covariate coding detail — but their exact coding
is not recoverable from the published methods, and this is where that
shows.</p>
<p>“Mouse group” is sex. The sexes came from different Jackson Labs
rooms and started with different microbiomes, so group, room, cage pair
and sex are one factor and cannot be separated. Under
<code>blocks = subject</code> it is constant within a mouse and has no
valid permutation distribution — read its <span
class="math inline">\(R^2\)</span>, not its <span
class="math inline">\(p\)</span>.</p>
<p><strong>The object reproduces the paper.</strong> Analysis continues
in <code>case_study.Rmd</code>.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
